aspnet6-razor/WiredBrainCoffeeAdmin/Components/ProductListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Components
{
    public class ProductListViewComponent : ViewComponent
    {
        private readonly IProductRepository _productRepository;

        public ProductListViewComponent(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IViewComponentResult Invoke(int count)
        {
            var items = _productRepository.GetAll();
            if (count > 0)
            {
                return View(items.Take(count).ToList());
            }

            return View(items);
        }
    }
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WiredBrainCoffeeAdmin.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Help.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.Design;
using WiredBrainCoffeeAdmin.Data;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class HelpModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {
            return Page();
        }
    }
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using System.Text;
using System.Text.Json;
using System;
using System.IO;
using System.Threading.Tasks;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public List<SurveyItem> SurveyResults { get; set; }
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            var rawJson = System.IO.File.ReadAllText("wwwroot/sampledata/survey.json");
            SurveyResults = JsonSerializer.Deserialize<List<SurveyItem>>(rawJson);

        }
    }
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Products/AddProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class AddProductModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        private IWebHostEnvironment webEnv;

        [BindProperty]
        public Product NewProduct { get; set; }

        public AddProductModel(IProductRepository productRepository, IWebHostEnvironment environment)
        {
            _productRepository = productRepository;
            this.webEnv = environment;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) { return Page();  }

            if (NewProduct.Upload is not null)
            {
                NewProduct.ImageFile = NewProduct.Upload.FileName;

                var file = Path.Combine(webEnv.ContentRootPath, "wwwroot/images/menu", NewProduct.Upload.FileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await NewProduct.Upload.CopyToAsync(fileStream);
                }
            }
            NewProduct.Created = DateTime.Now;

            _productRepository.Add(NewProduct);

            return RedirectToPage("ViewAllProducts");
        }
    }
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Products/EditProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class EditProductModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        private readonly IWebHostEnvironment _environment;

        [FromRoute]
        public int Id { get; set; }
        public Product EditProduct { get; set; }

        public EditProductModel(IProductRepository productRepository, IWebHostEnvironment environment)
        {
            _productRepository = productRepository;
            _environment = environment;
        }

        public void OnGet()
        {
            EditProduct = _productRepository.GetById(Id);
        }

        public async Task<IActionResult> OnPostEdit()
        {
            if (!ModelState.IsValid) { return Page(); }

            if (EditProduct.Upload is not null)
            {
                EditProduct.ImageFile = EditProduct.Upload.FileName;

                var file = Path.Combine(_environment.ContentRootPath, "wwwroot/images/menu", EditProduct.Upload.FileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await EditProduct.Upload.CopyToAsync(fileStream);
                }
            }
            EditProduct.Id = Id;
            EditProduct.Created = DateTime.Now;
            _productRepository.Update(EditProduct);

            return RedirectToPage("ViewAllProducts");
        }

        public IActionResult OnPostDelete()
        {
            this._productRepository.Delete(Id);
            return RedirectToPage("ViewAllProducts");
        }
    }
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Products/ViewAllProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class ViewAllProductsModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        public List<Product> Products { get; set; }
        public ViewAllProductsModel(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }
        public void OnGet()
        {
            Products = _productRepository.GetAll();
        }
    }
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Components/ProductList/Default.cshtml
@using WiredBrainCoffeeAdmin.Data
@model List<Product>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>Short description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td><img src="~/images/menu/@item.ImageFile" /></td>
                <td>@item.Name</td>
                <td>@item.Category</td>
                <td>@item.Price</td>
                <td>@item.ShortDescription</td>
                <td><a asp-page="EditProduct" asp-route-id="@item.Id">Edit</a></td>
            </tr>
        }
    </tbody>
</table>

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Help.cshtml
@page "/help"
@model WiredBrainCoffeeAdmin.Pages.HelpModel
@{
}

<h1 class="h2">Request Help</h1>
<hr />

<div class="row">
    <div class="col-md-6">
        
    </div>
    <div class="col-md-6">
        
    </div>
</div>


@section RightFooter {
    <p>Call us at 123-456</p>
    <p>Hours of operation: 9am to 4pm</p>
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/HelpWidget.cshtml
<div class="card">
    <div class="card-header">
        Request Help
    </div>
    <div class="card-body">
        <h5 class="card-title">Contact our IT Team</h5>
        <p class="card-text">Having an issue with the site? Let us know!</p>
        <a asp-page="help" class="btn btn-success">Request Help</a>
    </div>
</div>

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    Layout = "Shared/_LayoutFluid.cshtml";
}

<div class="container-fluid dashboard">
    <h1 class="h2">Welcome to Wired Brain Coffee!</h1>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <h2>Lastest Products</h2>
            <vc:product-list count="4"></vc:product-list>
            <h2>Latest Survey Result</h2>
            <table class="table table-striped table-bordered">
                @foreach(var item in Model.SurveyResults)
                {
                    <tr>
                        <td>@item.Question</td>
                        <td>@item.Answer</td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    The basic
                </div>
                <div class="card-body">
                    <p>Hello, today is @DateTime.Today.Date.ToString("dd MMM yyyy")</p>
                    @{
                        var temp = 55;
                    }
                    <p>The current temperature is @temp degree.</p>
                    @if (temp < 60)
                    {
                        <p>
                            We recommend a coat until it warms up
                            @(60 - temp) degrees.
                        </p>
                    }
                </div>
            </div>
            <partial name="HelpWidget" />
        </div>
    </div>
</div>

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/ProductForm.cshtml
@using WiredBrainCoffeeAdmin.Data
@model Product

<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="@Model.Name">Name</label>
        <input asp-for="@Model.Name" class="form-control" />
        <span asp-validation-for="@Model.Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.ShortDescription">Short Description</label>
        <input asp-for="@Model.ShortDescription" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Description">Description</label>
        <textarea asp-for="@Model.Description" class="form-control"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Price">Price</label>
        <input asp-for="@Model.Price" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Category">Category</label>
        <select asp-for="@Model.Category" class="form-control">
            <option value="Beverage">Beverage</option>
            <option value="Food">Food</option>
        </select>
    </div>
    @if(ViewContext.RouteData.Values["id"] is not null)
    {
        <div class="mb-3">
            <label asp-for="@Model.ImageFile">Current Image</label>
            <input type="hidden" asp-for="@Model.ImageFile" class="form-control" />
            <img src="~/images/menu/@Model.ImageFile" />
        </div>   
    }

    <div class="mb-3">
        <label asp-for="@Model.Upload">Image</label>
        <input asp-for="@Model.Upload" class="form-control" />
    </div>

    @if (ViewContext.RouteData.Values["id"] is not null)
    {
        <button class="btn btn-success" asp-page-handler="edit">Edit</button>
        <button class="btn btn-danger float-end" asp-page-handler="delete">Delete</button>
    }
    else
    {
        <button class="btn btn-success">Add</button>
    }
</form>

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Products/AddProduct.cshtml
@page "/products/add"
@model WiredBrainCoffeeAdmin.Pages.Products.AddProductModel
@{
}

<h1>Add New Product</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <partial name="ProductForm" model="@Model.NewProduct" />
    </div>
    <div class="col-md-6">
        <partial name="HelpWidget" />
    </div>
</div>

@section RightFooter {
    <img src="~/images/menu/cup.png" />
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Products/EditProduct.cshtml
@page "/products/edit/{id:int}"
@model WiredBrainCoffeeAdmin.Pages.Products.EditProductModel
@{
}

<h1>Edit Product @RouteData.Values["id"]</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <partial name="ProductForm" model="@Model.EditProduct" />
    </div>
    <div class="col-md-6">
        <partial name="HelpWidget" />
    </div>
</div>


@section RightFooter {
    <img src="~/images//menu/cappucino.png" />
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Products/ViewAllProducts.cshtml
@page "/products/all"
@model WiredBrainCoffeeAdmin.Pages.Products.ViewAllProductsModel
@{
}

<h1>All Products</h1>
<hr />

<vc:product-list count="0"></vc:product-list>

@section RightFooter {
    <img src="~/images/menu/salad-special.png" />
}

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Shared/Info.cshtml
<div class="card">
    <div class="card-header">
        The Basics
    </div>
    <div class="card-body">
        <p>Hello, today is @DateTime.Today.Date.ToString("MM/dd/yyyy").</p>
        @{
            var temperature = 58;
        }
        <p>The current temperature is @temperature degrees.</p>
        @if (temperature < 60)
        {
            <p>We recommend a coat until it warms up another @(65 - temperature) degrees!</p>
        }
    </div>
</div>

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wired Brain Coffee Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WiredBrainCoffeeAdmin.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page">Dashboard</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Products
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item">View All</a></li>
                                    <li><a class="dropdown-item">Add New</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled">Orders (Coming soon)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link">Help</a>
                            </li>
                        </ul>
                    </div>
                    <a class="navbar-brand float-right">Wired Brain Coffee</a>
                </div>
            </nav>
        </header>
        <main>
            @RenderBody()
        </main>
        <footer>
            <div class="row">
                <div class="col-md-4">
                    <p>&copy; 2022 - WiredBrainCoffeeAdmin</p>
                    <img id="logo" src="~/images/wired-brain-coffee-logo.png" />
                </div>
                <div class="col-md-4">
                    <p>1234 Wired Brain Way</p>
                    <p>Awesome City, CA 55555</p>
                    <p>Phone: 555-123-4567</p>
                    <p>Fax: 555-123-4567</p>
                </div>
                <div class="col-md-4">
                    <div class="footer-pic">
                        <p>Picture content goes here.</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

aspnet6-razor/WiredBrainCoffeeAdmin/Pages/Shared/_LayoutFluid.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wired Brain Coffee Admin</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment names="Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WiredBrainCoffeeAdmin.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" asp-page="/index">Dashboard</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Products
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-page="/products/viewallproducts">View All</a></li>
                                    <li><a class="dropdown-item" asp-page="/products/addproduct">Add New</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled">Orders (Coming soon)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-page="/help">Help</a>
                            </li>
                        </ul>
                    </div>
                    <a class="navbar-brand float-right">Wired Brain Coffee</a>
                </div>
            </nav>
        </header>
        <main>
            @RenderBody()
        </main>
        <footer>
            <div class="row">
                <div class="col-md-4">
                    <p>&copy; 2022 - WiredBrainCoffeeAdmin</p>
                    <img id="logo" src="~/images/wired-brain-coffee-logo.png" />
                </div>
                <div class="col-md-4">
                    <p>1234 Wired Brain Way</p>
                    <p>Awesome City, CA 55555</p>
                    <p>Phone: 555-123-4567</p>
                    <p>Fax: 555-123-4567</p>
                </div>
                <div class="col-md-4">
                    <div class="footer-pic">
                        @{
                            var urlPath = Context.Request.Path;
                        }

                        @switch (urlPath.Value.ToLower())
                        {
                            case "/":
                                <img src="~/images/menu/cake.png" />
                                break;
                            case "/products/addproduct":
                                <img src="~/images/menu/cup.png" />
                                break;
                            case "/products/viewallproducts":
                                <img src="~/images/menu/granola.png" />
                                break;
                            case "/help":
                                <img src="~/images/menu/waffles.png" />
                                break;
                        }
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>